Documentation/Migration.md
src/Task/Generic/CreateSymlinksTask.php

This reverts commit db5c9d17eb1a4bd2e0eceb9af25df3136bfc5761.
Relates: #11

Revert "[!!!] Switch argument order of symlink task to make more sense"

---

composer.json

[TASK] Downgrade symfony packages to ^2.8

---

composer.json
src/Command/SelfUpdateCommand.php
src/Integration/Factory.php

A self-update which uses padraic/phar-updater is added. The command will only be available when running the .phar file.

[FEATURE] Add self-update command

---

src/Command/DescribeCommand.php
src/Domain/Model/SimpleWorkflow.php
src/Domain/Model/Workflow.php

Describe workflow details

---

README.md

[TASK] Update documentation

---

README.md
Tests/Unit/Task/TYPO3/Flow/CopyConfigurationTaskTest.php
Tests/Unit/Task/TYPO3/Flow/CreateDirectoriesTaskTest.php
Tests/Unit/Task/TYPO3/Flow/RunCommandTaskTest.php
Tests/Unit/Task/TYPO3/Flow/SymlinkConfigurationTaskTest.php
Tests/Unit/Task/Transfer/RsyncTaskTest.php
src/Application/Neos/Flow.php
src/Application/Neos/FlowDistribution.php
src/Application/Neos/Neos.php
src/Task/Neos/Flow/CopyConfigurationTask.php
src/Task/Neos/Flow/CreateDirectoriesTask.php
src/Task/Neos/Flow/FlushCacheListTask.php
src/Task/Neos/Flow/FunctionalTestTask.php
src/Task/Neos/Flow/MigrateTask.php
src/Task/Neos/Flow/PublishResourcesTask.php
src/Task/Neos/Flow/RunCommandTask.php
src/Task/Neos/Flow/SetFilePermissionsTask.php
src/Task/Neos/Flow/SymlinkConfigurationTask.php
src/Task/Neos/Flow/SymlinkDataTask.php
src/Task/Neos/Flow/UnitTestTask.php
src/Task/Neos/Neos/ImportSiteTask.php
src/Task/TYPO3/CMS/CopyConfigurationTask.php

[!!!][TASK] Flow 4.0 compatibility

---

src/Task/Php/WebOpcacheResetExecuteTask.php

StreamContext of file_get_content() not working

---

README.md

remoteCommandExutionHandler > remoteCommandExecutionHandler
Resolves: #98

[BUGFIX] Fix typo in Readme

---

Tests/Unit/Task/Transfer/RsyncTaskTest.php
src/Task/Transfer/RsyncTask.php

Also add default or custom excludes if custom rsyncFlags are set
Resolves: #101

[!!!][TASK] Add excludes if rsyncFlags are set

---

src/ErrorMessageFactory.php
src/Task/TYPO3/CMS/AbstractCliTask.php
src/Task/TYPO3/CMS/CompareDatabaseTask.php
src/Task/TYPO3/CMS/FlushCachesTask.php

[TASK] Add deprecation warning for coreapi usage

---

Tests/Unit/Command/DescribeCommandTest.php
src/Command/DescribeCommand.php

[TASK] Output array options in describe command

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

[TASK] Add issue and pull request templates

---

Tests/Unit/Task/Php/WebOpcacheResetCreateScriptTaskTest.php
composer.json
composer.lock
src/Domain/Filesystem/Filesystem.php
src/Domain/Filesystem/FilesystemInterface.php
src/Domain/Generator/RandomBytesGenerator.php
src/Domain/Generator/RandomBytesGeneratorInterface.php
src/Task/Php/WebOpcacheResetCreateScriptTask.php

- The package ircmaxell/random-lib is not really maintained anymore. random_compat is a polyfill for the PHP7 native CSPRNG functions
- Write test for the Task WebOpcacheResetCreateScriptTask

[TASK] Replace package ircmaxell/random-lib with paragonie/random_compat

---

Tests/Unit/Command/DescribeCommandTest.php
src/Command/DescribeCommand.php

[BUGFIX] Show after and before tasks in describe command

---

Tests/Unit/Command/DescribeCommandTest.php
Tests/Unit/Task/Php/WebOpcacheResetCreateScriptTaskTest.php
src/Application/BaseApplication.php
src/Application/Neos/Flow.php
src/Application/Neos/FlowDistribution.php
src/Application/Neos/Neos.php
src/Application/TYPO3/CMS.php
src/Domain/Model/Application.php
src/Domain/Service/TaskManager.php
src/Task/Neos/Flow/FlushCacheListTask.php
src/Task/Php/WebOpcacheResetCreateScriptTask.php

[TASK] Using ::class for real class tasks

---

src/Task/TYPO3/CMS/AbstractCliTask.php
src/Task/TYPO3/CMS/CompareDatabaseTask.php
src/Task/TYPO3/CMS/FlushCachesTask.php

[BUGFIX] Fix wrong execution path with coreapi

---

Tests/Unit/Task/Composer/InstallTaskTest.php
src/Task/Composer/AbstractComposerTask.php

Cleanup
too complicated code for the result
Cleaner code
No

[TASK] Simplify additionalArguments in composer tasks

---

Tests/Unit/DeprecationMessageFactoryTest.php
src/DeprecationMessageFactory.php
src/Task/SourceforgeUploadTask.php
src/Task/TYPO3/CMS/AbstractCliTask.php
src/Task/TYPO3/CMS/CompareDatabaseTask.php
src/Task/TYPO3/CMS/CopyConfigurationTask.php
src/Task/TYPO3/CMS/FlushCachesTask.php

[TASK] Mark task CopyConfigurationTask as deprecated

---

Tests/Unit/Command/DescribeCommandTest.php
src/Application/Neos/Flow.php

Remove duplicate Composer LocalInstallTask
Resolves: #97
LocalInstallTask is run twice
LocalInstallTask is run once
No

[BUGFIX] Remove duplicate Composer\LocalInstallTask

---

src/Task/CleanupReleasesTask.php
src/Task/Composer/DownloadTask.php
src/Task/Composer/InstallTask.php
src/Task/CreateArchiveTask.php
src/Task/CreateDirectoriesTask.php
src/Task/DumpDatabaseTask.php
src/Task/Generic/CreateDirectoriesTask.php
src/Task/Generic/CreateSymlinksTask.php
src/Task/Git/PushTask.php
src/Task/Git/TagTask.php
src/Task/GitCheckoutTask.php
src/Task/LocalShellTask.php
src/Task/Package/GitTask.php
src/Task/Php/WebOpcacheResetCreateScriptTask.php
src/Task/Php/WebOpcacheResetExecuteTask.php
src/Task/RsyncFoldersTask.php
src/Task/ShellTask.php
src/Task/SourceforgeUploadTask.php
src/Task/StopTask.php
src/Task/SymlinkReleaseTask.php
src/Task/TYPO3/CMS/ActivatePackagesTask.php
src/Task/TYPO3/CMS/CompareDatabaseTask.php
src/Task/TYPO3/CMS/CopyConfigurationTask.php
src/Task/VarnishBanTask.php
src/Task/VarnishPurgeTask.php

This change adds annotations to many tasks which are needed for rendering useful api docs.

[TASK] Add task annotations

---

Tests/Unit/Domain/Model/SimpleWorkflowTest.php
src/Domain/Model/Workflow.php

Feature
If you remove a task it will be removed from every application
Now you can remove a task by application
No

[FEATURE] Let workflow remove task application based

---

Documentation/CliUsage/Index.rst
src/Command/DeployCommand.php
src/Command/DescribeCommand.php
src/Command/MigrateCommand.php
src/Command/ShowCommand.php
src/Command/SimulateCommand.php

As for now we do not offer any description for the available console commands.

[TASK] Add description for available console commands

---

render_phpdocs.sh

[TASK] Add title "ApiReference" for the the top level namespace

---

Documentation/Installation/Index.rst

[TASK] Review of installation chapter

---

Tests/Unit/Command/DescribeCommandTest.php
src/Command/DescribeCommand.php
src/Domain/Model/SimpleWorkflow.php

[TASK] Show enableRollback value in describe command

---

Documentation/DeploymentFlow/Index.rst
Documentation/Index.rst

[TASK] Add documentation chapter "Deployment Flow"

---

Documentation/Tasks/Index.rst

Fix some typos and improve the readability a bit.

[TASK] Revision of documentation chapters Tasks

---

src/Task/Neos/Flow/CopyConfigurationTask.php
src/Task/Neos/Flow/CreateDirectoriesTask.php
src/Task/Neos/Flow/FlushCacheListTask.php
src/Task/Neos/Flow/FunctionalTestTask.php
src/Task/Neos/Flow/MigrateTask.php
src/Task/Neos/Flow/PublishResourcesTask.php
src/Task/Neos/Flow/RunCommandTask.php
src/Task/Neos/Flow/SetFilePermissionsTask.php
src/Task/Neos/Flow/SymlinkConfigurationTask.php
src/Task/Neos/Flow/SymlinkDataTask.php
src/Task/Neos/Flow/UnitTestTask.php
src/Task/Neos/Neos/ImportSiteTask.php

Related #33
Just adds documentation to the neos / flow tasks

Add doc block for neos and flow tasks

---

src/Task/Php/WebOpcacheResetExecuteTask.php

[TASK] Add stream_context option to example for WebOpcacheResetExecuteTask

---

Tests/Unit/Domain/Model/NodeTest.php
Tests/Unit/Domain/Service/ShellCommandServiceTest.php
Tests/Unit/Task/TYPO3/Flow/CopyConfigurationTaskTest.php
src/Domain/Model/Deployment.php
src/Domain/Model/Node.php
src/Task/DumpDatabaseTask.php
src/Task/LocalShellTask.php
src/Task/Neos/Flow/CopyConfigurationTask.php
src/Task/Php/WebOpcacheResetCreateScriptTask.php
src/Task/RsyncFoldersTask.php
src/Task/Transfer/RsyncTask.php

The node class is very simple and implicit at the moment. I just introduce some simple api methods in order to configure a node.

[TASK] Add some simple api methods to configure node

---

src/Command/SelfUpdateCommand.php

[HOTFIX] Move instantiation of Updater to execute method

---

box.json
surf

[BUGFIX] Missing file PasswordSshLogin.expect in surf.phar

---

Tests/Unit/Task/BaseTaskTest.php
Tests/Unit/Task/Generic/RollbackTaskTest.php
composer.json
src/Command/RollbackCommand.php
src/Command/SimulateCommand.php
src/Domain/Model/Deployment.php
src/Domain/Model/RollbackWorkflow.php
src/Domain/Model/SimpleWorkflow.php
src/Exception/InvalidConfigurationException.php
src/Integration/Factory.php
src/Integration/FactoryInterface.php
src/Task/CleanupReleasesTask.php
src/Task/Generic/RollbackTask.php
src/functions.php

- Fixes #96
This is a new Feature
At the moment no rollback command exists
We now could rollback to the previous release by executing the surf rollback deployment
No breaking change

[TASK] Add rollback command

---

Documentation/ApiReference/Domain/Model/Deployment.rst
Documentation/ApiReference/Domain/Model/FailedDeployment.rst
Documentation/ApiReference/Domain/Model/RollbackWorkflow.rst
Documentation/ApiReference/Domain/Model/index.rst
Documentation/ApiReference/Exception/InvalidConfigurationException.rst
Documentation/ApiReference/Task/Generic/RollbackTask.rst
Documentation/ApiReference/Task/Generic/index.rst
Tests/Unit/Task/Generic/RollbackTaskTest.php
src/Command/RollbackCommand.php
src/Integration/Factory.php
src/Task/CleanupReleasesTask.php
src/Task/Generic/RollbackTask.php

- Symlink previous to the penultimate release after rollback
- Fix regression for --force parameter during deployment

[BUGFIX] Fix implementation of rollback command

---

Documentation/ApiReference/Domain/Model/HttpResponse.rst
Documentation/ApiReference/Domain/Model/index.rst
Documentation/ApiReference/Task/Test/HttpTestTask.rst
Tests/Unit/Task/Test/HttpTestTaskTest.php
box.json
composer.json
composer.lock
src/Domain/Model/HttpResponse.php
src/Task/Test/HttpTestTask.php

Refactoring and testability
No

[TASK] Use guzzle for the smoke tests

---

Documentation/Examples/Flow/Index.rst
Documentation/Examples/Index.rst
Documentation/Examples/Neos/Index.rst
Documentation/Examples/TYPO3/Index.rst
Documentation/Index.rst

[TASK] Issue 173 - Add documentation examples

---

Tests/Unit/Command/DescribeCommandTest.php
src/Command/DescribeCommand.php

[BUGFIX] Issue 216 - Show array key in describe command

---

Documentation/ApiReference/Task/LockDeploymentTask.rst
src/Domain/Service/TaskManager.php
src/Task/LockDeploymentTask.php
src/Task/UnlockDeploymentTask.php

[BUGFIX] Remove lock file on rollback

---

Documentation/ApiReference/Task/TYPO3/CMS/SymlinkDataTask.rst
Tests/Unit/Command/DescribeCommandTest.php
Tests/Unit/Task/TYPO3/CMS/SymlinkDataTaskTest.php
src/Application/TYPO3/CMS.php
src/Task/TYPO3/CMS/SymlinkDataTask.php

- Add new option symlinkUploadsFolder to make symlink for uploads folder configurable
Resolves: #246

[TASK] Make symlink for uploads folder configurable

---

Documentation/SmokeTesting/Index.rst

[TASK] Add example how to run smoke tests in test stage

---

Documentation/ApiReference/Task/Generic/CreateSymlinksTask.rst
src/Task/Generic/CreateSymlinksTask.php

This is a no brainer. Just configure the Options with OptionsResolver.

[TASK] Configure options with OptionsResolver

---

composer.json
composer.lock

In order to avoid a lot of boilerplate guard clauses i would like to use the widely used assert library webmozart/assert.

[TASK] Add library webmozart/assert for future use

---

Documentation/ApiReference/Task/Neos/Flow/FlushCacheListTask.rst
Tests/Unit/Task/Neos/Flow/FlushCacheListTaskTest.php
src/Task/Neos/Flow/FlushCacheListTask.php

- Use OptionsResolver for options configuration
- Move assertions / guard clauses to the very top of the method

[TASK] Refactor "FlushCacheListTask"

---

Tests/Unit/Task/Neos/Flow/UnitTestTaskTest.php
src/Task/Neos/Flow/UnitTestTask.php

- Add a test for the UnitTestTask
- Make assertion with Assert library webmozart/assert

[TASK] Refactor UnitTestTask for Flow applications

---

Documentation/ApiReference/Task/Neos/Flow/SetFilePermissionsTask.rst
Tests/Unit/Task/Neos/Flow/SetFilePermissionsTaskTest.php
src/Task/Neos/Flow/SetFilePermissionsTask.php

- Add test for the SetFilePermissionTask
- Assertion for the guard clause with library webmozart/assert

[TASK] Configure SetFilePermissionTask with OptionsResolver

---

Tests/Unit/Task/Neos/Flow/PublishResourcesTaskTest.php
src/Task/Neos/Flow/PublishResourcesTask.php

- Assert if application is of class Flow with library webmozart/assert

[TASK] Refactor PublishResourcesTask

---

src/Task/Neos/Neos/ImportSiteTask.php

- Assert done with library webmozart/assert

[TASK] Refactor ImportSiteTask

---

Tests/Unit/Task/Neos/Flow/FunctionalTestTaskTest.php
src/Task/Neos/Flow/FunctionalTestTask.php

- Assertion done with libary webmozart/assert
- Create UnitTest for task

[TASK] Refactor FunctionalTestTask

---

Documentation/Index.rst
Documentation/Introduction/Index.rst

[TASK] Add description and introduction chapter

---

Tests/Unit/Task/TYPO3/CMS/SymlinkDataTaskTest.php
src/Cli/Symfony/Logger/ConsoleHandler.php
src/Domain/Service/ShellCommandService.php
src/Task/Neos/Flow/SymlinkConfigurationTask.php
src/Task/TYPO3/CMS/AbstractCliTask.php
src/Task/Test/HttpTestTask.php

docker run -v $(pwd):/app rector/rector:0.5.5 process /app/src --autoload-file /app/vendor/autoload.php --level code-quality
docker run -v $(pwd):/app rector/rector:0.5.5 process /app/Tests --autoload-file /app/vendor/autoload.php --level code-quality
Tests are nearly untouched
Code quality

[TASK] Apply rector code-quality level

---

Documentation/ApiReference/Task/SourceforgeUploadTask.rst

[BUGFIX] Fix typo

---

Tests/Unit/Domain/Model/Clock/SystemClockTest.php
Tests/Unit/Task/CleanupReleasesTaskTest.php
src/Domain/Clock/ClockException.php
src/Domain/Clock/ClockInterface.php
src/Domain/Clock/SystemClock.php
src/Task/CleanupReleasesTask.php

- Resolves #81
Add a new option "onlyRemoveReleasesOlderThan" for the CleanupReleasesTask.
You can use every valid notation of the strtotime function like "1 day ago".

[TASK] Keep releases by Age

---

src/Command/SelfUpdateCommand.php
src/Domain/Clock/ClockException.php
src/Domain/Model/Deployment.php
src/Exception/DeploymentLockedException.php
src/Exception/TaskExecutionException.php
src/Task/Composer/AbstractComposerTask.php
src/Task/DumpDatabaseTask.php
src/Task/Git/AbstractCheckoutTask.php
src/Task/Neos/Flow/CopyConfigurationTask.php
src/Task/Package/GitTask.php

[TASK] Code cleanup

---

composer.json

- Start new development version 3.0

[TASK] Add branch alias for master

---

Documentation/Tasks/Index.rst

[BUGFIX] Use correct namespaces in docs

---

composer.json
composer.lock
src/Command/SelfUpdateCommand.php

- Due to a "bug" in dependency humbug/phar-updater we downgrade to version 1.0.5

[BUGFIX] Downgrade to padraic/phar-updater version 1.0.5

---

.editorconfig
Documentation/Examples/TYPO3/Index.rst
src/Application/TYPO3/CMS.php
tests/Unit/Command/DescribeCommandTest.php

Followup for https://github.com/TYPO3/Surf/pull/328 as the references have been forgotten to delete

[CLEANUP] Remove deprecated tasks followup

---

src/Command/DeployCommand.php

Bug fix
```
Available commands:
deploy    Deploys the application with the given name
```
```
Available commands:
deploy    Deploys the application with the given name
```

[BUGFIX] Set correct description for deploy command

---

src/Domain/Filesystem/Filesystem.php
src/Domain/Filesystem/FilesystemInterface.php
src/Domain/Generator/IdGenerator.php
src/Domain/Generator/IdGeneratorInterface.php
src/Task/CreateArchiveTask.php
tests/Unit/Task/CreateArchiveTaskTest.php

Feature
Check options without OptionsResolver. A lot of cluttered boilerplate code
Use OptionsResolver to configure options of task
No

[TASK] Use OptionsResolver for CleanupReleasesTask

---

src/Task/GitCheckoutTask.php
tests/Unit/Task/GitCheckoutTaskTest.php

Feature
Options are not configured with the OptionsResolver
Configure options with OptionsResolver and get rid of a lot of boilerplate checks
No

[TASK] Use OptionsResolver for GitCheckoutTask

---

src/Task/Git/PushTask.php
tests/Unit/Task/Git/PushTaskTest.php

Feature
A lot of boilerplate for checking options
Using OptionsResolver to configure options
No

[FEATURE] Use OptionsResolver for PushTask

---

src/Task/Php/WebOpcacheResetCreateScriptTask.php

[BUGFIX] Set scriptIdentifier for WebOpcacheResetExecuteTask in simulation

---

src/Task/CleanupReleasesTask.php
src/Task/DumpDatabaseTask.php
src/Task/Generic/CreateDirectoriesTask.php
src/Task/Generic/CreateSymlinksTask.php
src/Task/Generic/RollbackTask.php
src/Task/Git/PushTask.php
src/Task/Git/TagTask.php
src/Task/LocalShellTask.php
src/Task/LockDeploymentTask.php
src/Task/Neos/Flow/CopyConfigurationTask.php
src/Task/Neos/Flow/FlushCacheListTask.php
src/Task/Neos/Flow/FunctionalTestTask.php
src/Task/Neos/Flow/MigrateTask.php
src/Task/Neos/Flow/PublishResourcesTask.php
src/Task/Neos/Flow/RunCommandTask.php
src/Task/Neos/Flow/SetFilePermissionsTask.php
src/Task/Neos/Flow/SymlinkConfigurationTask.php
src/Task/Neos/Flow/SymlinkDataTask.php
src/Task/Neos/Flow/UnitTestTask.php
src/Task/Neos/Neos/ImportSiteTask.php
src/Task/RsyncFoldersTask.php
src/Task/ShellTask.php
src/Task/StopTask.php
src/Task/SymlinkReleaseTask.php
src/Task/TYPO3/CMS/CreatePackageStatesTask.php
src/Task/TYPO3/CMS/SymlinkDataTask.php
src/Task/Transfer/RsyncTask.php
src/Task/Transfer/ScpTask.php
src/Task/UnlockDeploymentTask.php

- Add annotation codeCoverageIgnore for task where simulate method is nothing more than a delegation to the execute method of task

[TASK] Add annotation codeCoverageIgnore

---

.github/FUNDING.yml

Determined with:
https://github.com/TYPO3/Surf/graphs/contributors?from=2019-05-07&to=2020-05-07&type=c

[TASK] Add top 3 contributors of the last year

---

.github/workflows/tests.yaml

Currently the workflow is not executed for PRs against 2.0 branch

Execute Tests on push and pull requests

---

.github/workflows/php_cs_fixer.yaml
Documentation/DeploymentFlow/Index.rst
composer.lock
src/Domain/Model/Deployment.php
src/Task/Test/HttpTestTask.php
tests/Unit/Domain/Model/DeploymentTest.php

Resolves: #398 
Feature
If your project root is a level deeper than your `.git` folder, you can set the relative project root path in the deployment configuration with `$deployment->setRelativeProjectRootPath('htdocs')`.

[FEATURE] Add relativeProjectRootPath to deployment

---

src/Domain/Model/Deployment.php
src/Task/Composer/AbstractComposerTask.php
src/Task/Transfer/RsyncTask.php

Bugfix for #403 
Use correct paths in Composer and Rsync Task

[BUGFIX] Use correct paths in Composer and Rsync Task

---

src/Domain/Model/Deployment.php
src/Task/Composer/AbstractComposerTask.php
src/Task/Transfer/RsyncTask.php

Bugfix for #403 
Use correct paths in Composer and Rsync Task

[BUGFIX] Use correct paths in Composer and Rsync Task (#405)

---

src/Domain/Service/TaskFactory.php
tests/Unit/Domain/Service/TaskFactoryTest.php

Bugfix
You can not create custom tasks otherwise the container is throwing an exception
Allow creation of so called synthetic services during runtime.
No

Allow custom tasks creation

---

src/Domain/Service/ShellCommandService.php
src/Task/Transfer/RsyncTask.php

Bug fix for https://github.com/TYPO3/Surf/issues/424

[BUGFIX] Properly initialize passwordSshLoginScriptPathAndFilename

---

Resources/services.yaml

fix
rollback command didn't work
Additionally sorted the keys alphabetically.

Add RollbackWorkflow to services.yaml

---

src/Application/Neos/Flow.php
src/Domain/Model/RollbackWorkflow.php
src/Task/Neos/Flow/FlushCacheListTask.php
src/Task/Neos/Flow/WarmUpCacheTask.php
tests/Unit/Command/DescribeCommandTest.php
tests/Unit/Task/Neos/Flow/WarmUpCacheTaskTest.php

Resolves: #427
Feature
Caches are warmed up automatically with the next call to flow
Warmup flow caches during deployment
No

[FEATURE] Add flow warmup task

---

Documentation/SmokeTesting/Index.rst

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.

[TASK] Update TYPO3 repository URL

---

.github/workflows/code_coverage.yaml
.github/workflows/phpstan.yaml
.github/workflows/tests.yaml
src/Task/Git/AbstractCheckoutTask.php
tests/Unit/Task/GitCheckoutTaskTest.php

Update vulnerable github actions

---

src/Task/Neos/Flow/CopyConfigurationTask.php

Bug fix
https://github.com/TYPO3/Surf/issues/627#issuecomment-1424998343
No.

[BUGFIX] Cast port option to string for escapeshellarg calls

---

Resources/services.php
composer.json
composer.lock
src/Domain/Version/ComposerVersionChecker.php
src/Domain/Version/VersionCheckerInterface.php
src/Task/TYPO3/CMS/AbstractCliTask.php
src/Task/TYPO3/CMS/SetUpExtensionsTask.php
tests/Unit/Task/TYPO3/CMS/SetUpExtensionsTaskTest.php

TASK: Check typo3 console version via composer

---

src/Domain/Version/ComposerVersionChecker.php
src/Task/TYPO3/CMS/AbstractCliTask.php
src/Task/TYPO3/CMS/SetUpExtensionsTask.php
tests/Unit/Task/TYPO3/CMS/SetUpExtensionsTaskTest.php

TASK: Catch OutofboundsException

---

Resources/services.php

Just a tiny inconsistency between the advertised version number and what you download.

TASK: Increase version number to 3.3.10

---

src/Cli/Symfony/ConsoleKernel.php

@YetiCGN This should fix the issue #735

TASK: Change hardcoded directories for Symfony Kernel

---

src/Cli/Symfony/ConsoleKernel.php
src/Task/Generic/CreateSymlinksTask.php
tests/Unit/Task/BaseTaskTest.php
tests/Unit/Task/Generic/CreateSymlinksTaskTest.php

TASK: Create option not to create symlinks

---

src/Task/Composer/DownloadTask.php
src/Task/CreateArchiveTask.php
src/Task/DumpDatabaseTask.php
src/Task/Git/PushTask.php
src/Task/Git/TagTask.php

TASK: Deprecate some old Tasks

---

bin/surf
composer.json
composer.lock
phpstan-baseline.neon
src/Cli/Symfony/ConsoleKernel.php
tests/Unit/KernelAwareTrait.php

TASK: Move away from symfony/http-kernel

---

composer.json
composer.lock
src/Task/TYPO3/CMS/AbstractCliTask.php

TASK: Make surf TYPO3 version 12 compatible

---

src/Task/Neos/Flow/CopyConfigurationTask.php
tests/Unit/Task/Neos/Flow/CopyConfigurationTaskTest.php

[BUGFIX] Do not double escape path
