TYPO3/Surf

bin/surf
composer.json
surf

The surf executable is moved to the root directory and a loop
is used for detecting the correct autoload.php file (inspired
by the concept used of phpunit).
Resolves: #8

[BUGFIX] Move surf executable and fix autoload include

---

src/Application/BaseApplication.php

The options for the CreateDirectoriesTask and the
CreateSymlinksTask are now set as application options
in the registerTasks() call of the BaseApplication.
This makes sure that multiple applications do not override
the settings which can lead to unexpected behavior.

[BUGFIX] Application specific directory and symlink options

---

src/Task/Php/WebOpcacheResetCreateScriptTask.php

because standard uses base64 charset which also includes `/` and this results in an error while creating the script. So you have to set a scriptIdentifier as an option in your deployment script which, I think, isn't necessary because this should be the default.

[TASK] Add characters parameter to generateString 

---

Tests/Unit/Task/Generic/CreateDirectoriesTaskTest.php
Tests/Unit/Task/TYPO3/Flow/CreateDirectoriesTaskTest.php
src/Task/Generic/CreateDirectoriesTask.php
src/Task/TYPO3/Flow/CreateDirectoriesTask.php

With commit 642f7c3 the base directory for creating these directories
changed from the deployment base to the release path, causing the
directories to be created in the wrong place.
This commit adds a new option to allow specifing a different base
directory and the flow task can then provide this with the deployment
base.
Related: #25

[BUGFIX] Fix creating shared/Data directories in Flow application

---

Tests/Unit/Task/BaseTaskTest.php

Adding the missing ampersand makes all the difference. Otherwise the $responses array can not be modified in the test methods.

[BUGFIX] Allow TaskTests to fake shell responses

---

src/Command/DescribeCommand.php

Previously the describe command threw and exception when printing
the value of ` TYPO3\Surf\Task\Generic\CreateDirectoriesTask[directories]`
or other options with array values.

FIX: No exception when describing non-scalar options

---

README.md
Tests/Unit/Domain/Model/SimpleWorkflowTest.php
src/Application/TYPO3/Flow.php
src/Application/TYPO3/FlowDistribution.php
src/Application/TYPO3/Neos.php
src/Task/TYPO3/CMS/RunCommandTask.php
src/Task/TYPO3/Flow/CreateDirectoriesTask.php
src/Task/TYPO3/Flow/FunctionalTestTask.php
src/Task/TYPO3/Flow/MigrateTask.php
src/Task/TYPO3/Flow/PublishResourcesTask.php
src/Task/TYPO3/Flow/RunCommandTask.php
src/Task/TYPO3/Flow/SetFilePermissionsTask.php
src/Task/TYPO3/Flow/UnitTestTask.php
src/Task/TYPO3/Neos/ImportSiteTask.php

Removes the TYPO3 family prefix and uses the guideline
for the Neos family.

[TASK] Update naming scheme for Flow/Neos

---

src/Application/TYPO3/Flow.php

This is breaking because older projects which still use Flow 2.* have to change this setting.
Resolves: #43

[!!!][TASK] Updates Flow default version to 3.0

---

src/Task/Neos/Flow/SetFilePermissionsTask.php

Hey,
i had trouble running "SetFilePermissionsTask".
```
"PHP Warning:  escapeshellarg() expects parameter 1 to be string, array given"
```
Changing `[$arguments]` to `$arguments` fixed the issue

Make $arguments flat nested array to be able to convert it to string

---

Tests/Unit/Task/TYPO3/Flow/CopyConfigurationTaskTest.php
Tests/Unit/Task/Transfer/RsyncTaskTest.php
src/Task/Neos/Flow/CopyConfigurationTask.php
src/Task/Transfer/RsyncTask.php

Scenario: Public key authentication is set up, but we configured Surf to use a password instead. It makes sense in our environment, because Surf is run by Jenkins and some Jenkins stages should only be allowed to run if the server password is provided.
It is already done for remote SSH commands ([here](https://github.com/TYPO3/Surf/blob/51dd7ebd3c0ea5d2e6b74fb606e4ca3db3e909ff/src/Domain/Service/ShellCommandService.php#L131-L133)), but Rsync commands currently fail in this case, because public key authentication kicks in and succeeds before expect can enter the password.
```
send: spawn id exp6 not open     while executing "send -- "$password\r""     (file "[...]/PasswordSshLogin.expect" line 14)
```

Disable public key authentication if password is provided

---

src/Task/Php/WebOpcacheResetExecuteTask.php

- This is useful for example to execute the task if we have to provide Basic Authentication

[FEATURE] Add stream_context option to WebOpcacheResetExecuteTask

---

src/Task/Php/WebOpcacheResetExecuteTask.php

to be able to rollback.
We had this problem in 2 of our projects now so I've thought it would be interesting for the world.
The warnings are often overseen by others and so you definitely notice that something went wrong.

[TASK] Let WebOpcacheResetExecuteTask throw an error

---

Tests/Unit/Domain/Model/ApplicationTest.php
src/Domain/Model/Application.php

The path for shared assests is unconfigurable fixed string in
application model. This change adds a new option "sharedDirectory"
which is used to get the shared path.
The related logic has been put in a separate getter "getSharedDirectory"

[FEATURE] make shared path configurable

---

Tests/Unit/Task/Generic/CreateSymlinksTaskTest.php
src/Task/Generic/CreateSymlinksTask.php

The CreateGenericSymlinkTask creates relative symlinks by default in
application release path.
This commit adds the option "genericSymlinksBaseDir" to allow
a different base directory for relative symlinks.
Suggestions for better option naming  are welcome.

[FEATURE] make base directory for relative symlinks configurable

---

Tests/Unit/Task/Composer/InstallTaskTest.php
src/Task/Composer/AbstractComposerTask.php
src/Task/Composer/InstallTask.php

This patch moves general composer functionality to an abstract class and implements the possibility to pass additional arguments to composer commands.
E.g. if you use Surf within a CI pipeline, the building PHP environment in the task runner is not necessary. Using config.platform in composer.json will also fake the environment on dev systems where you want to fail an composer command if requirements are not fulfilled.

Be able to pass additional arguments to composer commands

---

.gitignore
Documentation/Includes.txt
Documentation/Index.rst
Documentation/Migration.md
Documentation/Migration/Index.rst
Documentation/Quickstart/Flow/Index.rst
Documentation/Quickstart/Index.rst
Documentation/Quickstart/Neos/Index.rst
Documentation/Quickstart/Other/Index.rst
Documentation/Quickstart/TYPO3/Index.rst
Documentation/Settings.cfg
Documentation/Settings.yml
README.md

This change add the necessary boilerplate
for the new documentation.
The setup will then be also compatible with
the TYPO3 documentation project.
See the updated readme for details.
Relates: #34

[TASK] Add documentation boilerplate

---

.travis.yml
composer.json
composer.lock
src/Task/DumpDatabaseTask.php

The actual typo3_console project does support
- symfony/console:^4
- symfony/progress:^4
If you use PHP 7.2 (and typo3_console), composer
installs ^4 of mentioned symfony packages.
Updating these typo3/surf reduces composer conflicts
in such situations.
Fixes: #104
Related: #129

[TASK] Raise version constraints for symfony/console and symfony/process

---

src/ErrorMessageFactory.php
src/Task/SourceforgeUploadTask.php

The SourceforgeUploadTask is in my opinion very outdated these days. We should remove this task in Version 3.0.0. To do so we should mark this task as deprecated as early as possible.

[TASK] Mark SourceforgeUploadTask as deprecated

---

render_phpdocs.sh

The folder with .gitkeep is called ApiReference, while the default
within render_phpdocs.sh was APIReference. This would not work on case
sensitive file systems.

BUGFIX: Fix case collision of ApiReference folder

---

composer.json
composer.lock

On the hand we are requiring monolog as a concrete implementation of the PSR-3 standard, but on the other hand we requiring the common interface for logging libraries psr/log itself. 
This gives the wrong impression that you could choose one of the existing concrete implementations of the PSR-3 standard.

[CLEANUP] Remove dependency psr/log

---

composer.json

This patch allows the actual version of paragonie/random_compat.

[TASK] Allow paragonie/random_compat v9.99

---

Documentation/Index.rst
Documentation/Usage/Index.rst

- Renamed "Getting Started" to "Usage"
- Move "Installation" up in the menu
- Removed link to "Getting Started" (now "Usage") from "Installation" page

[TASK] Change documentation navigation structure to simplify reading

---

Tests/Unit/Command/DescribeCommandTest.php
src/Application/TYPO3/CMS.php

Resolves: #257
Add `.ddev` to default rsyncExcludes of TYPO3
`.ddev` get synced if it's not excluded
`.ddev` is excluded by default for TYPO3
Just if someone ships data from that folder. Very unlikely.

[TASK] Add .ddev to default rsync excludes of TYPO3

---

Documentation/Examples/TYPO3/Index.rst

Since #177 is closed, scriptBasePath is not necessary anymore for TYPO3 CMS
Docs

[TASK] Remove unnecessary scriptBasePath option

---

src/Application/BaseApplication.php

As localhost that installs the application is not the same system that runs the application, it is useless to check the platform requirements.

[TASK] Ignore platform requirements for LocalInstallTask

---

Documentation/Index.rst

As is customary for official TYPO3 documentation. This way, it is possible to link to the start page by using interphinx linking, such as:
:ref:`t3surf:start`

Add "start" label on start page

---

src/Task/Php/WebOpcacheResetCreateScriptTask.php

Bugfix
Simulation is broken if no scriptIdentifier is set
Resolve #291

[BUGFIX] Set scriptIdentifier for WebOpcacheResetExecuteTask in simulation

---

src/Task/LocalShellTask.php
tests/Unit/Task/LocalShellTaskTest.php

Feature
Options are configured with OptionsResolver
Using OptionsResolver to configure all options. Remove boilerplate checks and add tests for the task
No

[TASK] Add OptionsResolver for LocalShellTask

---

src/Application/BaseApplication.php
src/Application/Neos/Flow.php
src/Application/Neos/Neos.php
src/Application/TYPO3/CMS.php
src/Domain/Model/Application.php
src/Task/Php/WebOpcacheResetCreateScriptTask.php
tests/Unit/Command/DescribeCommandTest.php
tests/Unit/Task/Php/WebOpcacheResetCreateScriptTaskTest.php
tests/Unit/Task/Transfer/RsyncTaskTest.php

Bugfix
Since TYPO3 9 the "official" web directory is 'public'. This is also default in many other frameworks like Laravel or Symfony.
web root directory is 'web'
web root directory is 'public'
Users who rely on surf defaults must change the option "webDirectory" to 'web'

[BUGFIX] Use 'public' as webDirectory

---

src/Domain/Model/TaskInHistory.php
src/Domain/Service/TaskFactory.php
src/Domain/Service/TaskManager.php
tests/Unit/Domain/Service/TaskFactoryTest.php
tests/Unit/Domain/Service/TaskManagerTest.php

- Create class TaskFactory. The new class is responsible for the real creation of the task. First step to depedency injection container
Feature
The TaskManager is responsible for the execution and creation of the task
Separate the creation and execution of the task.

[TASK] Add more unit tests for class TaskManager

---

src/Task/TYPO3/CMS/CreatePackageStatesTask.php

Migrate: Please add "@php vendor/bin/typo3cms install:generatepackagestates" in
your root composer.json file in the post-autoload-dump scripts section.

[TASK] Deprecate CreatePackageStatesTask

---

Tests/Unit/Task/TYPO3/CMS/FlushCachesTaskTest.php
src/Task/TYPO3/CMS/FlushCachesTask.php

Small feature change the default `--force` parameter of the FlushCachesTask
`--force` can't changed or left out and was removed with typo3-console 6.2
#396 
The default `--force`  can be changed to `--files-only` or just an empty array
No

Make it possible to change the parameter of FlushCachesTask

---

Tests/Unit/Task/Neos/Flow/FlushCacheListTaskTest.php
src/Task/Neos/Flow/FlushCacheListTask.php

Resolves: #412
Releases: 2.1
Bugfix
PHP warning if an array is given as option because trim exprect a string.
Check the type and handle the array.
No

[BUGFIX] Prevent PHP warning by checking the type

---

src/Cli/Symfony/ConsoleKernel.php
src/Integration/Factory.php

- For the phar context we need a cache and log directory for the DI-Container outside of the phar file

[BUGFIX] Use available cache and log directory

---

src/Integration/Factory.php
tests/Unit/Integration/FactoryTest.php

Bugfix (see description below)
* **What is the current behavior?**
If you have a `.surf`-Folder in your project, surf only checks for config-files within that folder.  
That causes trouble, if you want to use your default-deployment from your home directory in one case, but have a local `.surf`-Folder for other cases. Adding `--configurationPath` is annoying at this point.
* **What is the new behavior?**
If the configuration-file with the give deployment name wasn't found locally, it checks for the same file in the home-dir before failing.
I don't think so.

BUGFIX: Also check for deploy-config in home-dir

---

README.md

The shortcut `https://docs.typo3.org/surf` is configured manually and thus error-prone as it can link to outdated documentation. Using `https://docs.typo3.org/other/typo3/surf/master/en-us/` always links to the latest version of the documentation.
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/159 for further details.

[TASK] Replace error-prone shortcut to documentation in `README.md`

---

src/Task/Transfer/RsyncTask.php

escapeshellarg expects the parameter to be a string.
Relates: cd5a2593
Bug fix
RsyncTask fails in PHP 8.1 if a port has been set.
no

[BUGFIX] Fix parameter type for escapeshellarg(port)

---

src/Domain/Model/Deployment.php
tests/Unit/Domain/Model/Clock/SystemClockTest.php
tests/Unit/Task/CleanupReleasesTaskTest.php

strftime() was deprecated in PHP 8.1. It is replaced by the equivalent
date() call.
Bug fix
Depending on the PHP error_reporting, this is reported as `PHP Deprecated: Function strftime() is deprecated in /var/www/html/build/deployment/vendor/typo3/surf/src/Domain/Model/Deployment.php on line 103`
no

[TASK] replace deprecated strftime()

---

src/Task/Generic/CreateSymlinksTask.php

Quality-of-life improvement.
Using `symlinks`, Surf would set symlinks to non-existent targets when being used to configure shared directories.
Targets are created as empty directories if the path does not exist yet.
no
Trying to update the outdated Surf example code on https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/DeployTYPO3.htm …

[TASK] Create symlink targets if they do not exist yet

---

.github/workflows/tests.yaml

An additional test in GitHub workflow
There currently is no test, if surf itsself can be executed after installing all composer packages.
In an additinal job, all composer packages are installed and `bin/surf` is executed and must not fail. The test is done with multiple PHP versions.
No.
I think, multiple problems (#760 #770 #771) could have been detected …

FEATURE: Check if bin/surf can be executed with different PHP versions

---

Resources/services.php
src/Domain/Model/Deployment.php
src/Domain/Service/TaskFactory.php
tests/Unit/Domain/Service/CustomTask.php
tests/Unit/Domain/Service/TaskFactoryTest.php

TASK: Inject Logger for custom task

---

Resources/services.php
composer.json
src/Cli/Symfony/ConsoleKernel.php
src/Domain/Model/Deployment.php
src/Domain/Model/FailedDeployment.php
src/Domain/Service/TaskFactory.php
src/Integration/Factory.php
tests/Unit/Command/DescribeCommandTest.php
tests/Unit/Domain/Model/DeploymentTest.php
tests/Unit/Domain/Model/RollbackWorkflowTest.php
tests/Unit/Domain/Model/SimpleWorkflowTest.php
tests/Unit/Domain/Service/ShellCommandServiceTest.php
tests/Unit/Domain/Service/TaskFactoryTest.php
tests/Unit/Domain/Service/TaskManagerTest.php
tests/Unit/Integration/FactoryTest.php
tests/Unit/Task/BaseTaskTest.php
tests/Unit/Task/CleanupReleasesTaskTest.php

[TASK] Use constructor injection for Container
